# Generated by Django 3.1 on 2020-09-08 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('first_name', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('age', models.IntegerField(default=18)),
                ('goal', models.CharField(choices=[('bulk', 'Bulk'), ('cut', 'Cut'), ('tone', 'Tone')], default='', max_length=30)),
                ('experience', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='', max_length=30)),
                ('city', models.CharField(choices=[('san luis obispo', 'San Luis Obispo'), ('atascadero', 'Atascadero')], default='', max_length=30)),
                ('gym_membership', models.CharField(choices=[('ASI Recreation Center', 'ASI Recreation Center')], default='', max_length=30)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
